# schemas.py

# Pydantic is the validation library built into FastAPI
# BaseModel is the parent class all schemas inherit from
from pydantic import BaseModel, Field

# Optional means a field is not required
# List is for returning lists of items
from typing import Optional, List

# For timestamp fields
from datetime import datetime


# ─────────────────────────────────────────────────────
# HOW SCHEMAS WORK:
#
# For each table we create 3 schemas:
#
# 1. XxxBase    → common fields shared by create and response
# 2. XxxCreate  → what the USER sends when creating (inherits Base)
# 3. Xxx        → what WE send back as response (inherits Base)
#
# Why 3? Because:
# - When creating, user doesn't send id or created_at (we generate those)
# - When responding, we want to include id and created_at
# ─────────────────────────────────────────────────────


# ═══════════════════════════════════════
# CATEGORY SCHEMAS
# ═══════════════════════════════════════

class CategoryBase(BaseModel):
    # Field() lets us add extra info about each field
    # description= shows in the auto-generated API docs
    # example= shows a sample value in docs
    name: str = Field(..., description="Category name", example="Electronics")

    # Optional means this field is not required
    # None means if not provided, default value is None
    description: Optional[str] = Field(None, description="Category description")


class CategoryCreate(CategoryBase):
    # CategoryCreate inherits ALL fields from CategoryBase
    # Right now it's the same, but we keep them separate
    # because in the future we might add fields only for creation
    pass


class Category(CategoryBase):
    # This is the RESPONSE schema - what we send back to the user
    # It includes id and created_at which are generated by the system
    id: int
    created_at: datetime

    # This is CRITICAL for SQLAlchemy integration
    # Without this, Pydantic would refuse to read SQLAlchemy model objects
    # orm_mode=True tells Pydantic: "you might receive SQLAlchemy objects,
    # not just plain dictionaries — handle them correctly"
    class Config:
        from_attributes = True


# ═══════════════════════════════════════
# SUPPLIER SCHEMAS
# ═══════════════════════════════════════

class SupplierBase(BaseModel):
    name: str = Field(..., description="Supplier name", example="Tech Distributors Ltd")
    email: Optional[str] = Field(None, example="supplier@email.com")
    phone: Optional[str] = Field(None, example="+92-300-1234567")
    address: Optional[str] = Field(None, example="123 Main St, Lahore")


class SupplierCreate(SupplierBase):
    pass


class Supplier(SupplierBase):
    id: int
    created_at: datetime

    class Config:
        from_attributes = True


# ═══════════════════════════════════════
# PRODUCT SCHEMAS
# ═══════════════════════════════════════

class ProductBase(BaseModel):
    name: str = Field(..., description="Product name", example="iPhone 15")

    description: Optional[str] = Field(None, example="Latest Apple smartphone")

    # gt=0 means "greater than 0" - price cannot be negative or zero
    price: float = Field(..., gt=0, description="Product price", example=999.99)

    # ge=0 means "greater than or equal to 0"
    quantity: int = Field(0, ge=0, description="Stock quantity", example=50)

    # The threshold below which we show a low stock warning
    low_stock_threshold: int = Field(10, ge=0, example=10)

    sku: Optional[str] = Field(None, description="Stock Keeping Unit", example="ELEC-001")

    # Foreign keys - which category and supplier this product belongs to
    # Both optional because a product might not have these assigned yet
    category_id: Optional[int] = Field(None, example=1)
    supplier_id: Optional[int] = Field(None, example=1)


class ProductCreate(ProductBase):
    # Same as base for now
    # In future you might add fields like "initial_stock_note"
    # that are only needed at creation time
    pass


class ProductUpdate(BaseModel):
    # ProductUpdate is COMPLETELY optional fields
    # Why? Because when updating, user might only want to
    # change the price — they shouldn't need to resend everything
    # This is called a PATCH update (partial update)
    name: Optional[str] = None
    description: Optional[str] = None
    price: Optional[float] = Field(None, gt=0)
    quantity: Optional[int] = Field(None, ge=0)
    low_stock_threshold: Optional[int] = Field(None, ge=0)
    sku: Optional[str] = None
    category_id: Optional[int] = None
    supplier_id: Optional[int] = None


class Product(ProductBase):
    # Response schema includes system-generated fields
    id: int
    created_at: datetime

    # These bring in the FULL related objects
    # So when we return a product, we also return its full category
    # and supplier details — not just the IDs
    category: Optional[Category] = None
    supplier: Optional[Supplier] = None

    class Config:
        from_attributes = True


# ═══════════════════════════════════════
# TRANSACTION SCHEMAS
# ═══════════════════════════════════════

class TransactionBase(BaseModel):
    # Literal means this field can ONLY be "IN" or "OUT"
    # This matches our Enum in models.py
    transaction_type: str = Field(..., example="IN")

    # Must be at least 1 — you can't transact 0 items
    quantity: int = Field(..., gt=0, description="Number of units", example=10)

    note: Optional[str] = Field(None, example="Restocked from supplier")

    # Which product this transaction is for
    product_id: int = Field(..., example=1)


class TransactionCreate(TransactionBase):
    pass


class Transaction(TransactionBase):
    id: int
    created_at: datetime

    # Include full product details in response
    product: Optional[Product] = None

    class Config:
        from_attributes = True


# ═══════════════════════════════════════
# DASHBOARD SCHEMA
# ═══════════════════════════════════════
# This is a special schema — it doesn't map to a table
# It's just a shape for the dashboard summary response

class DashboardStats(BaseModel):
    total_products: int
    total_categories: int
    total_suppliers: int
    low_stock_count: int
    total_stock_value: float      # sum of (price × quantity) for all products
    recent_transactions: List[Transaction] = []

    class Config:
        from_attributes = True